deepl_api_token: ENC[AES256_GCM,data:R1D7HtXNQLJxxAC/fkGWRPxJ2TzJsyRbvLqa3i4dCl4Pse6YgCWf,iv:BJnzkMScu64VMwC74J4mHG29IyT85/muUyX8Kp50ksA=,tag:P6Ch2pQ6D/59DHiZGLCqDA==,type:str]
github_api_token: ENC[AES256_GCM,data:LyS2r1iytZ2Gf1HuyRGOIgBWNhoF0WJQqtpGgrNIsApdkD2siQaHxw==,iv:LcnloQ5/RpzC0uDp7KMeVqlt6E8xZhdPAGmCandbVoc=,tag:DxQx0nIMaN1PEo+0bnv66Q==,type:str]
keepassxc_password: ENC[AES256_GCM,data:a0Klp7Edi3Y80A==,iv:vFsMazu62LIU3b0qAO37I1AS0jsV+x2dlbZYYlSjTJs=,tag:gSNvcbvSqLCBhtp6iY/prw==,type:str]
firefox_extensions:
  keepassxc-browser: ENC[AES256_GCM,data:zaZIq7ZoqOjlPuFYPHspLnoep7bUJYm5SKWi21fv5YFDxJlFwvCqv3c0HTXEIZYQKIDyW/evg19kE1v0EtRIXJPTcBc4uU9e2mPbcryyK5lzN9oGRSU5SBKrEbg8wm2BJ1J+Euou9foj/eFlNW1Uqkl37axdMga/vH4yPhwhfiCxwFZnl++wnBe5u84Fl5Y+I7GzNIwaWasLITx0e57PyW06cRy1A/SYF5upo99k92//9xWNRHOhx2J2DBmapi/rCt5aoprU8UisGC722axlbmqKz0KCuaV/+UcDLKFIyBTC8UiE3fdd3w==,iv:at7/TWwXGiMELdvxmhG+HUiaqzcoEBe/EMOyUb/Pok8=,tag:mc1TW/57lWGidam0kZxxOw==,type:str]
  languagetool: ENC[AES256_GCM,data:4CabDPr9H8M01uc7BJgeMUDJs9pZneawTaWIAbxadlu8x67mNinrWuZMiZqrc1ansTxDsYFrLBs/lIW8OOu+MXtZfh398wy4ugg=,iv:WSYRlBSVf4BTh3W5nIDtmcMnrnjKwZ44SGwiisNj0C4=,tag:CJ5cvlpjTtsx3IOwF22sJA==,type:str]
  simple-translate: ENC[AES256_GCM,data:eFA2Fx7OBit+HYcNGDasTXxHzwxfgQKkCOYNV9hTJ8Wt1R0BJHXQyeiznmdrgFxWejkK5xjx/1ZbooCTwTr+g/j2,iv:5vEBHG83hvh9MEbqIUam1LZ12yYyitkqr0IQkmqjDUg=,tag:IeQoCp1fDHhZ/5CDNrA4/g==,type:str]
  tab-session-manager: ENC[AES256_GCM,data:HHQMsDi0s92R3+OuL160tVOGDV2cqZ1DsNM0ySdW2vRyUk61AbTgPR61CqZ6aQaHv6G3N/yiLX/3vrJmG4w66tK+Vq5W9sMaOwUv7S2T8GgFHcSbj5iCKA5D4kPV8yAIXPVLruEva0rAGPzcwzz/9aikpR0NBVe5S/oVDV1oVEzXvHurDTFO5jHedeB1cUWJQTIwSg4Z4a8r+TYL4EU2/zwT049ZFGG77EKyGpC3KPV1cgDX/Hx9/ES2g+SqCFsiEx5VB7MueH7qQRLhXlAWDqM6Px4h57LI8n2sLjcEdhYW+MwAG5K/6dyUpNZLSXG7A3L9MbLSsPYOkp2siZHJ6Mje5zS2lwbSighNAtgwly3UZg/tY97H7enS3pqVqvSKW5l6EEJSnjn/c9133sbHSZKsBKNMlGK81teApQseATQHhJlloEsWEKFan9T/l36M+GUhhW+WctsHvZyyOXjlV7mm8huvuIaudI276moPLWYiBfD6YaJ0w5ZEb6XwEb3HcFxlTrpY1GWWG+r838zFQ9yRE7DDA+3pR3R8TVzlrJZWZx4mWifcTMIMMg8sEJqLhbVF1Qbqa6Sxaec=,iv:yhvzbwLcQenuLDa1HZwHVBiR0dagyqIgN5O6bL65arM=,tag:zSazweo7an4riMT9ndcBjQ==,type:str]
sops:
  age:
    - recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS0RMa1VkT0pOMFB1R3dy
        bFMvMy9TWmFKT1lMYTk0b0h5YSs4K2htaWhnCkFaRkM2YUJWeWVJTjNYQTluUm9K
        OGxFaGR3eGtaK1d2K3BHUUhZQU5ZdEkKLS0tIE1WY1FrZ2psUjJOKzhJV0dnQUUv
        N0JpOWVNYzJFTnNROWhiWHJycGdPbG8KmcLCgF9qkkVobN4j5o9yPwmWIQ54VYlI
        QSJBY8OIYw9tAe73d5ihtMN9wfvbyXuPAtct9WrTnqAIGSePa1chvw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWnZMNHVlYk1UUVppZkYx
        MHJWR3UxOHJZd2lOakZ1ejJPNGQvLzZRS3lBCnU3ekVUNVU0QlNESVpicUxDQXdD
        cTBMVU1mUEFSRU5jcWNodE1xYnljeFkKLS0tICsxb04rUit3WTZoWnJTQ2MxQ1Fm
        Z0ZxeHYvTXZFYUhuRTlyTDRzS21paTgKWp5SbQn4WwYqy/BBCrEisWXlDSx64hbo
        CTICMwJAR+nJlrcayS1ZbChPYETbNRj5dvBwbKwL4q5o2TFXz9eYJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T11:02:41Z"
  mac: ENC[AES256_GCM,data:dbCN2Uy3zc7VgftHIkPaweTXZnZ17EAr/QL4zznClumyMM+JR+u1Y6CgCdm9K/BGKSXjT9xIGJ+uEaOIc3HXGlA6/gcR/i2LulHoEXu98+HTfr7M76FE3k2V45Np+kOOiGX6fowJ/1y6aHl0NHKGmqa0snMOFJd7zLq4D8F9tZ0=,iv:aW7QMkqNHCYA53/xPsXIGHTALCDRvGb1tsng1UMImF0=,tag:oLXAkFN55aaFHiX5QNTUXg==,type:str]
  pgp:
    - created_at: "2025-08-13T18:47:33Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAoYfyCcZ8Qp3FDyCRrFMM1oks+ejYI3aPGZPQMpikjk8w
        K1wXL/CAWhQlm8GurUcM51LwD680qqlKTsvDzoIz845HDBlPPGzW18s23obB/FPa
        0lwBmhcC1S50qcjPCVrVyUcEtUtJArS3rEvJ95ks4jHTFHF6p9du52B9TtqJ4v5g
        4Z9GZoDW9oqykdF82Aea7sMNqpm4RpVugGr1ymTjA60uzEL5YFiYCIJ18BQ2Ug==
        =6dw7
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.11.0
